"""
EarnSafe AI Engine — ai_service.py
====================================
Loads pre-trained models from disk (generated by train_models.py).
Exposes the same two functions the backend already calls:

    predict_risk(zone, delivery_persona, tier)          → premium + risk score
    detect_claim_anomaly(rain_mm, hours_worked, ...)    → fraud flag

SETUP:
    1. Run train_models.py once on your machine
    2. Place the 3 output files in:  backend/app/services/models/
       - risk_model.cbm
       - fraud_model.pkl
       - zone_risk_map.pkl
    3. Replace backend/app/services/ai_service.py with this file
"""

import os
import pickle
import logging
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────
# MODEL PATHS
# ─────────────────────────────────────────────────────────────────
_MODELS_DIR = Path(__file__).parent / "models"

_RISK_MODEL_PATH     = _MODELS_DIR / "risk_model.cbm"
_FRAUD_MODEL_PATH    = _MODELS_DIR / "fraud_model.pkl"
_ZONE_MAP_PATH       = _MODELS_DIR / "zone_risk_map.pkl"

# ─────────────────────────────────────────────────────────────────
# LOAD MODELS AT STARTUP (once)
# ─────────────────────────────────────────────────────────────────
print("⚡ Loading EarnSafe AI models...")

# --- CatBoost Risk Model ---
risk_model = CatBoostClassifier()
if _RISK_MODEL_PATH.exists():
    risk_model.load_model(str(_RISK_MODEL_PATH))
    print(f"✅ Risk model loaded from {_RISK_MODEL_PATH}")
else:
    # Fallback: train a minimal model so the server doesn't crash
    # Replace this by running train_models.py
    logger.warning("risk_model.cbm not found — using minimal fallback. Run train_models.py!")
    _fallback_df = pd.DataFrame([
        {"Zone": "Velachery", "Delivery_Persona": "Food", "Month": 8,
         "Forecast_Rain_mm": 60, "Forecast_Temp_C": 28, "AQI_PM25": 40,
         "Wind_KPH": 10, "External_Disruption": "Heavy Rainfall"},
        {"Zone": "Anna Nagar", "Delivery_Persona": "Food", "Month": 4,
         "Forecast_Rain_mm": 0, "Forecast_Temp_C": 40, "AQI_PM25": 30,
         "Wind_KPH": 8, "External_Disruption": "Extreme Heat"},
        {"Zone": "OMR", "Delivery_Persona": "Food", "Month": 1,
         "Forecast_Rain_mm": 2, "Forecast_Temp_C": 29, "AQI_PM25": 25,
         "Wind_KPH": 12, "External_Disruption": "None"},
        {"Zone": "T Nagar", "Delivery_Persona": "Food", "Month": 11,
         "Forecast_Rain_mm": 45, "Forecast_Temp_C": 27, "AQI_PM25": 80,
         "Wind_KPH": 5, "External_Disruption": "Severe Waterlogging"},
    ])
    risk_model = CatBoostClassifier(
        iterations=50, depth=3,
        cat_features=["Zone", "Delivery_Persona", "External_Disruption"],
        verbose=0,
    )
    risk_model.fit(_fallback_df, [0, 0, 0, 1])

# --- IsolationForest Fraud Model ---
fraud_model = None
if _FRAUD_MODEL_PATH.exists():
    with open(_FRAUD_MODEL_PATH, "rb") as f:
        fraud_model = pickle.load(f)
    print(f"✅ Fraud model loaded from {_FRAUD_MODEL_PATH}")
else:
    from sklearn.ensemble import IsolationForest
    logger.warning("fraud_model.pkl not found — using minimal fallback. Run train_models.py!")
    _X_fallback = np.array([
        [40.0, 4.0, 0.92, 0.60, 0.80, 1],
        [0.5,  6.0, 0.10, 0.95, 0.05, 4],
        [30.0, 3.0, 0.88, 0.55, 0.75, 0],
        [55.0, 5.0, 0.95, 0.70, 0.90, 2],
    ])
    fraud_model = IsolationForest(contamination=0.10, random_state=42)
    fraud_model.fit(_X_fallback)

# --- Zone Risk Map ---
zone_risk_map: dict = {}
if _ZONE_MAP_PATH.exists():
    with open(_ZONE_MAP_PATH, "rb") as f:
        zone_risk_map = pickle.load(f)
    print(f"✅ Zone risk map loaded ({len(zone_risk_map)} zones)")
else:
    # Default Chennai zone risks
    zone_risk_map = {
        "Velachery":      {"flood": 0.85, "heat": 0.60, "aqi": 0.55},
        "Anna Nagar":     {"flood": 0.35, "heat": 0.65, "aqi": 0.50},
        "T Nagar":        {"flood": 0.60, "heat": 0.70, "aqi": 0.65},
        "OMR":            {"flood": 0.40, "heat": 0.55, "aqi": 0.40},
        "Tambaram":       {"flood": 0.50, "heat": 0.60, "aqi": 0.45},
        "Adyar":          {"flood": 0.70, "heat": 0.58, "aqi": 0.48},
        "Perambur":       {"flood": 0.45, "heat": 0.65, "aqi": 0.70},
        "Chrompet":       {"flood": 0.55, "heat": 0.62, "aqi": 0.50},
        "Sholinganallur": {"flood": 0.75, "heat": 0.55, "aqi": 0.42},
        "Kodambakkam":    {"flood": 0.50, "heat": 0.68, "aqi": 0.60},
    }

print("✅ EarnSafe AI Engine ready.\n")

# ─────────────────────────────────────────────────────────────────
# TIER BASE RATES (₹/week)
# ─────────────────────────────────────────────────────────────────
_TIER_BASE_RATES = {
    "basic":    29.0,
    "standard": 49.0,
    "pro":      89.0,
}

# ─────────────────────────────────────────────────────────────────
# PUBLIC API — same signatures as before, now with real models
# ─────────────────────────────────────────────────────────────────

def predict_risk(
    zone: str,
    delivery_persona: str,
    tier: str,
    # Optional: pass real weather data from Open-Meteo
    # If not provided, zone-based seasonal defaults are used
    rain_mm: float | None = None,
    temp_c: float | None = None,
    aqi_pm25: float | None = None,
    wind_kph: float | None = None,
    month: int | None = None,
    active_disruption: str | None = None,
) -> dict:
    """
    Run the CatBoost model to get an AI risk score and dynamic weekly premium.

    Returns:
        ai_risk_score       float 0.0–1.0
        weekly_premium_inr  float ₹
        zone                str
        active_disruption   str
    """
    from datetime import datetime

    clean_zone    = zone.strip().title()
    clean_persona = delivery_persona.strip().title()
    clean_tier    = tier.strip().lower()

    # Get zone-specific risk profile (default to medium if unknown zone)
    zone_profile = zone_risk_map.get(clean_zone, {"flood": 0.50, "heat": 0.60, "aqi": 0.50})

    # Use real weather if provided, otherwise derive from zone + month
    if month is None:
        month = datetime.now().month

    # Season-aware defaults for Chennai
    if 6 <= month <= 10:  # monsoon
        default_rain = zone_profile["flood"] * 45
        default_temp = 28.0
    elif month in (3, 4, 5):  # summer
        default_rain = 5.0
        default_temp = 35 + zone_profile["heat"] * 6
    else:
        default_rain = 10.0
        default_temp = 29.0

    rain_mm   = rain_mm  if rain_mm  is not None else default_rain
    temp_c    = temp_c   if temp_c   is not None else default_temp
    aqi_pm25  = aqi_pm25 if aqi_pm25 is not None else 30.0 + zone_profile["aqi"] * 50
    wind_kph  = wind_kph if wind_kph is not None else 12.0

    # Determine disruption label from weather if not provided
    if active_disruption is None:
        if rain_mm > 50 and zone_profile["flood"] > 0.6:
            active_disruption = "Severe Waterlogging"
        elif rain_mm > 20:
            active_disruption = "Heavy Rainfall"
        elif temp_c > 40:
            active_disruption = "Extreme Heat"
        elif aqi_pm25 > 75:
            active_disruption = "Severe AQI"
        else:
            active_disruption = "None"

    input_data = pd.DataFrame([{
        "Zone":                clean_zone,
        "Delivery_Persona":    clean_persona,
        "Month":               month,
        "Forecast_Rain_mm":    round(rain_mm, 1),
        "Forecast_Temp_C":     round(temp_c, 1),
        "AQI_PM25":            round(aqi_pm25, 1),
        "Wind_KPH":            round(wind_kph, 1),
        "External_Disruption": active_disruption,
    }])

    try:
        probability = float(risk_model.predict_proba(input_data)[:, 1][0])
    except Exception as e:
        logger.warning(f"CatBoost inference failed: {e} — defaulting to 0.5")
        probability = 0.5

    base_rate = _TIER_BASE_RATES.get(clean_tier, 49.0)
    # Premium formula: base × (1 + risk_score)
    # High risk zone in monsoon → up to 2× base
    final_premium = round(base_rate * (1.0 + probability), 2)

    return {
        "ai_risk_score":      round(probability, 2),
        "weekly_premium_inr": final_premium,
        "zone":               clean_zone,
        "active_disruption":  active_disruption,
        # Extra context for the premium_service breakdown
        "weather_inputs": {
            "rain_mm":  round(rain_mm, 1),
            "temp_c":   round(temp_c, 1),
            "aqi_pm25": round(aqi_pm25, 1),
            "wind_kph": round(wind_kph, 1),
            "month":    month,
        },
    }


def detect_claim_anomaly(
    reported_rain_mm: float,
    hours_worked_before_claim: float,
    location_match_score: float,
    # New anti-spoofing features (default to neutral if not available)
    claim_to_coverage_ratio: float = 0.5,
    platform_activity_drop: float = 0.7,
    prior_claims_count: int = 0,
) -> dict:
    """
    Run the IsolationForest model on a claim to detect anomalies.

    Features (6):
        reported_rain_mm          — how much rain was reported
        hours_worked_before_claim — hours lost claimed
        location_match_score      — GPS vs cell tower match (0=mismatch, 1=match)
        claim_to_coverage_ratio   — claim amount / daily cap
        platform_activity_drop    — how much delivery activity dropped
        prior_claims_count        — number of previous claims by this user

    Returns:
        is_anomaly    bool
        anomaly_label str  "FLAGGED" | "NORMAL"
        anomaly_score float  (lower = more anomalous, IsolationForest score)
    """
    claim_data = np.array([[
        max(0.0, reported_rain_mm),
        max(0.0, hours_worked_before_claim),
        max(0.0, min(1.0, location_match_score)),
        max(0.0, min(1.0, claim_to_coverage_ratio)),
        max(0.0, min(1.0, platform_activity_drop)),
        max(0, prior_claims_count),
    ]])

    prediction   = fraud_model.predict(claim_data)[0]   # 1=normal, -1=anomaly
    anomaly_score = float(fraud_model.score_samples(claim_data)[0])

    return {
        "is_anomaly":    prediction == -1,
        "anomaly_label": "FLAGGED" if prediction == -1 else "NORMAL",
        "anomaly_score": round(anomaly_score, 4),
    }
